### ISSUE TITLE
ModuleNotFoundError: No module named 'huicv.evaluation'

### ISSUE THREAD

**Issue by Hshuqin** [ucas-vg/TOV_mmdetection#1]
ModuleNotFoundError: No module named 'huicv.evaluation'

Hello, I don't know why I get this error when I run retinanet

**Comment by yinglang** [comment]
Thanks for the feedback, it may be caused by the wrong URL for submoudle we given, We will fixed as soon as we can now.

**Comment by Hshuqin** [comment]
> Thanks for the feedback, it may be caused by the wrong URL for submoudle we given, We will fixed as soon as we can now.

Thanks, I ran retinanet 50, trained to 2000+ iterations, cls_loss is nan, and I didn't change all the parameters?

**Comment by yinglang** [comment]
After downloading TOV_mmdetection, the huicv need to be downloaded to TOV_mmdetection/huicv. 
```
git clone https://gitee.com/ucas-vg/TOV_mmdetection # git clone https://github.com/ucas-vg/TOV_mmdetection
cd TOV_mmdetection
# download code for evaluation
git clone https://gitee.com/ucas-vg/huicv # git clone https://github.com/yinglang/huicv/
```

The huicv project contains the evaluation code.

**Comment by Hshuqin** [comment]
otherwise，in the Readme,md，this url ：https://github.com/ucas-vg/TOV_mmdetection/blob/main/exp/doc/code_modify.md can not visit，I would like to know what configuration needs to be changed to run on the original mmdetection， thanks

**Comment by Hshuqin** [comment]
otherwise，in the Readme,md，this url ：https://github.com/ucas-vg/TOV_mmdetection/blob/main/exp/doc/code_modify.md can not visit，I would like to know what configuration needs to be changed to run on the original mmdetection， thanks

**Comment by yinglang** [comment]
> > Thanks for the feedback, it may be caused by the wrong URL for submoudle we given, We will fixed as soon as we can now.
> 
> Thanks, I ran retinanet 50, trained to 2000+ iterations, cls_loss is nan, and I didn't change all the parameters?

For the unkown reason, the loss of training retinanet in TinyPerson with mmdetection is easy to get nan.  (maybe 9 times got nan if totoally running 10 times). Using [this config with grad clip strategy](https://github.com/ucas-vg/TOV_mmdetection/blob/main/configs2/TinyPerson/base/retinanet_r50_fpns4_1x_TinyPerson640.py) instead the [origin one](https://github.com/ucas-vg/TOV_mmdetection/blob/main/configs2/TinyPerson/base/retinanet_r50_fpns4_1x_TinyPerson640.py), the loss come more stable.

**Comment by yinglang** [comment]
> otherwise，in the Readme,md，this url ：https://github.com/ucas-vg/TOV_mmdetection/blob/main/exp/doc/code_modify.md can not visit，I would like to know what configuration needs to be changed to run on the original mmdetection， thanks

Thanks for your reminding，the file has been added.

**Comment by Hshuqin** [comment]
> > otherwise，in the Readme,md，this url ：https://github.com/ucas-vg/TOV_mmdetection/blob/main/exp/doc/code_modify.md can not visit，I would like to know what configuration needs to be changed to run on the original mmdetection， thanks
> 
> Thanks for your reminding，the file has been added.

Thank you so much!
