### ISSUE TITLE
How would we understand the folder 'exp'?

### ISSUE THREAD

**Issue by freshn** [ucas-vg/TOV_mmdetection#10]
@yinglang  I have no idea what is saved in the folder 'exp'. The '*.json' file in that folder can be evaluated by huicv/evaluatation/evaluate_tiny.py but not the one in 'work_dir/.../*.json'. Could you explain what is this folder used for? How can I evaluate the results based on the training log under folder 'work_dir' instead of 'exp'? Thank you.

**Comment by yinglang** [comment]
There are some tools to help experiment, and some temeproal file.
'exp/.../.json' was the inference result of latest evaluation. it is just a temperal file.
