### ISSUE TITLE
Where can I get the file 'instances_merge2017.json'?

### ISSUE THREAD

**Issue by missyoudaisy** [ucas-vg/TOV_mmdetection#14]
Hello, I just wanna know where can I get the file 'instances_merge2017.json'?

**Comment by yinglang** [comment]
this is same problem as [#https://github.com/ucas-vg/TinyBenchmark/issues/20](https://github.com/ucas-vg/TinyBenchmark/issues/20)

**Comment by missyoudaisy** [comment]
ok，thanks
