### ISSUE TITLE
ModuleNotFoundError: No module named 'huicv'  and MR

### ISSUE THREAD

**Issue by sxy1122** [ucas-vg/TOV_mmdetection#15]
ModuleNotFoundError: No module named 'huicv'

After the training, I eval it, and I also imported the huicv package into the project. Why did he make an error and say that there was no module.

python huicv/evaluation/evaluate_tiny.py --res exp/latest_result.json --gt data/tiny_set/mini_annotations/tiny_set_test_all.json --detail

In addition, there is another question. The verification accuracy has been obtained during training. What do you mean in your project is to send the. JSON file obtained from training to the huicv module for verification again?

**Comment by yinglang** [comment]
Maybe you need setup the proejct by 
```
python setup.py build develop
```

If the problem is still  exists after setup, you can run with that
```
PYTHONPATH=. python huicv/evaluation/evaluate_tiny.py --res xxx
```
