### ISSUE TITLE
Weird ranges of bbox during evaluation.

### ISSUE THREAD

**Issue by freshn** [ucas-vg/TOV_mmdetection#5]
The command I run is:

export GPU=1 && CONFIG="fcos_standard_r50_caffe_fpns4_gn-head_1x_TinyPerson640" && CUDA_VISIBLE_DEVICES=6 tools/dist_train.sh configs2/TinyPerson/base/${CONFIG}.py $GPU 

During the evaluation every four epochs, part of the messages are shown like:

2021-08-05 12:27:13,251 - mmdet - INFO - Evaluating bbox...
INFO:mmdet:Evaluating bbox...
Loading and preparing results...
DONE (t=1.22s)
creating index...
index created!
{'cocoGt': <mmdet.datasets.api_wrappers.coco_api.COCO object at 0x7f65ba763050>, 'cocoDt': <pycocotools.coco.COCO object at 0x7f667c403b50>, 'evalImgs': defaultdict(<class 'list'>, {}), 'eval': {}, '_gts': defaultdict(<class 'list'>, {}), '_dts': defaultdict(<class 'list'>, {}), 'params': <huicv.evaluation.expand_cocofmt_eval.ExpandParam object at 0x7f65bbde3610>, '_paramsEval': {}, 'stats': [], 'ious': {}, 'use_ignore_attr': True, 'use_iod_for_ignore': True, 'ignore_uncertain': True, 'iod_th_of_iou_f': <function <lambda> at 0x7f65bc762200>}
{'evaluate_standard': 'tiny', 'catIds': [1], 'iouThrs': array([0.25, 0.5 , 0.75]), 'recThrs': array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ]), 'maxDets': [200], 'areaRng': [[1, 10000000000.0], [1, 400], [1, 64], [64, 144], [144, 400], [400, 1024], [1024, 10000000000.0]], 'areaRngLbl': ['all', 'tiny', 'tiny1', 'tiny2', 'tiny3', 'small', 'reasonable'], 'useCats': 1, 'iouType': 'bbox', 'useSegm': None}

I am wondering are the ranges listed in 'areaRng' correctly? It seems the ranges do not align with the labels in 'areaRngLbl'. From my understanding, the ranges should be [[1,inf],[2,20],[2,8],[8,12],[12,20],[20,32],[32,inf]]. Is there anything I misunderstand?

**Comment by yinglang** [comment]
Hi, your output has no problem. The ouput is area range of object, and waht your understand is size range. while area=size*size.

`
'areaRng': [[1, 10000000000.0], [1, 400], [1, 64], [64, 144], [144, 400], [400, 1024], [1024, 10000000000.0]],
[[1,inf],[2,20],[2,8],[8,12],[12,20],[20,32],[32,inf]].
`

Beside there has no 1x1 object, so [2, 8] is same as [1, 8].

**Comment by freshn** [comment]
I got it. Thank you.
